import { Attrs } from "elt"
export function Exclude(attrs?: Attrs): SVGElement
export function Asclepius(attrs?: Attrs): SVGElement
export function Coffee(attrs?: Attrs): SVGElement
export function PencilCircle(attrs?: Attrs): SVGElement
export function Headlights(attrs?: Attrs): SVGElement
export function Shrimp(attrs?: Attrs): SVGElement
export function MapTrifold(attrs?: Attrs): SVGElement
export function KeyReturn(attrs?: Attrs): SVGElement
export function DotsNine(attrs?: Attrs): SVGElement
export function CaretDown(attrs?: Attrs): SVGElement
export function Train(attrs?: Attrs): SVGElement
export function ArrowsOutLineHorizontal(attrs?: Attrs): SVGElement
export function Resize(attrs?: Attrs): SVGElement
export function FlowerLotus(attrs?: Attrs): SVGElement
export function Rainbow(attrs?: Attrs): SVGElement
export function Browsers(attrs?: Attrs): SVGElement
export function DiceTwo(attrs?: Attrs): SVGElement
export function Webcam(attrs?: Attrs): SVGElement
export function Sneaker(attrs?: Attrs): SVGElement
export function SplitVertical(attrs?: Attrs): SVGElement
export function Boules(attrs?: Attrs): SVGElement
export function ArrowsInLineVertical(attrs?: Attrs): SVGElement
export function Tire(attrs?: Attrs): SVGElement
export function ToiletPaper(attrs?: Attrs): SVGElement
export function FediverseLogo(attrs?: Attrs): SVGElement
export function UmbrellaSimple(attrs?: Attrs): SVGElement
export function ShieldWarning(attrs?: Attrs): SVGElement
export function CardsThree(attrs?: Attrs): SVGElement
export function ShootingStar(attrs?: Attrs): SVGElement
export function ExclamationMark(attrs?: Attrs): SVGElement
export function ShuffleSimple(attrs?: Attrs): SVGElement
export function Fingerprint(attrs?: Attrs): SVGElement
export function HeartHalf(attrs?: Attrs): SVGElement
export function FilePng(attrs?: Attrs): SVGElement
export function Desktop(attrs?: Attrs): SVGElement
export function ArrowLineRight(attrs?: Attrs): SVGElement
export function BatteryVerticalEmpty(attrs?: Attrs): SVGElement
export function CassetteTape(attrs?: Attrs): SVGElement
export function PottedPlant(attrs?: Attrs): SVGElement
export function RowsPlusBottom(attrs?: Attrs): SVGElement
export function SealCheck(attrs?: Attrs): SVGElement
export function CrosshairSimple(attrs?: Attrs): SVGElement
export function ArrowSquareIn(attrs?: Attrs): SVGElement
export function Cards(attrs?: Attrs): SVGElement
export function Drop(attrs?: Attrs): SVGElement
export function Wrench(attrs?: Attrs): SVGElement
export function HandCoins(attrs?: Attrs): SVGElement
export function Eyedropper(attrs?: Attrs): SVGElement
export function Towel(attrs?: Attrs): SVGElement
export function CodesandboxLogo(attrs?: Attrs): SVGElement
export function Wine(attrs?: Attrs): SVGElement
export function Rocket(attrs?: Attrs): SVGElement
export function FilePdf(attrs?: Attrs): SVGElement
export function AlignBottom(attrs?: Attrs): SVGElement
export function Chair(attrs?: Attrs): SVGElement
export function Martini(attrs?: Attrs): SVGElement
export function SelectionPlus(attrs?: Attrs): SVGElement
export function CigaretteSlash(attrs?: Attrs): SVGElement
export function LinkSimpleBreak(attrs?: Attrs): SVGElement
export function PuzzlePiece(attrs?: Attrs): SVGElement
export function CirclesThreePlus(attrs?: Attrs): SVGElement
export function InstagramLogo(attrs?: Attrs): SVGElement
export function Tabs(attrs?: Attrs): SVGElement
export function PlusMinus(attrs?: Attrs): SVGElement
export function ArrowElbowRight(attrs?: Attrs): SVGElement
export function GlobeX(attrs?: Attrs): SVGElement
export function FolderPlus(attrs?: Attrs): SVGElement
export function Scan(attrs?: Attrs): SVGElement
export function Garage(attrs?: Attrs): SVGElement
export function Scroll(attrs?: Attrs): SVGElement
export function Code(attrs?: Attrs): SVGElement
export function TrashSimple(attrs?: Attrs): SVGElement
export function AmazonLogo(attrs?: Attrs): SVGElement
export function GooglePlayLogo(attrs?: Attrs): SVGElement
export function Seat(attrs?: Attrs): SVGElement
export function Rug(attrs?: Attrs): SVGElement
export function Building(attrs?: Attrs): SVGElement
export function BriefcaseMetal(attrs?: Attrs): SVGElement
export function NumberSquareFour(attrs?: Attrs): SVGElement
export function HardDrive(attrs?: Attrs): SVGElement
export function BezierCurve(attrs?: Attrs): SVGElement
export function LessThan(attrs?: Attrs): SVGElement
export function Champagne(attrs?: Attrs): SVGElement
export function SquareSplitHorizontal(attrs?: Attrs): SVGElement
export function Play(attrs?: Attrs): SVGElement
export function MicrosoftExcelLogo(attrs?: Attrs): SVGElement
export function Headset(attrs?: Attrs): SVGElement
export function Spiral(attrs?: Attrs): SVGElement
export function SunDim(attrs?: Attrs): SVGElement
export function AlignTopSimple(attrs?: Attrs): SVGElement
export function StackPlus(attrs?: Attrs): SVGElement
export function CarBattery(attrs?: Attrs): SVGElement
export function LadderSimple(attrs?: Attrs): SVGElement
export function Flower(attrs?: Attrs): SVGElement
export function Network(attrs?: Attrs): SVGElement
export function FunnelSimpleX(attrs?: Attrs): SVGElement
export function ChatsCircle(attrs?: Attrs): SVGElement
export function CellSignalFull(attrs?: Attrs): SVGElement
export function ForkKnife(attrs?: Attrs): SVGElement
export function CaretCircleUpDown(attrs?: Attrs): SVGElement
export function DeviceTablet(attrs?: Attrs): SVGElement
export function CaretLineRight(attrs?: Attrs): SVGElement
export function TextIndent(attrs?: Attrs): SVGElement
export function AppleLogo(attrs?: Attrs): SVGElement
export function User(attrs?: Attrs): SVGElement
export function CurrencyDollarSimple(attrs?: Attrs): SVGElement
export function ToggleRight(attrs?: Attrs): SVGElement
export function Placeholder(attrs?: Attrs): SVGElement
export function WechatLogo(attrs?: Attrs): SVGElement
export function Shuffle(attrs?: Attrs): SVGElement
export function Eye(attrs?: Attrs): SVGElement
export function ChatDots(attrs?: Attrs): SVGElement
export function Television(attrs?: Attrs): SVGElement
export function Taxi(attrs?: Attrs): SVGElement
export function Monitor(attrs?: Attrs): SVGElement
export function FingerprintSimple(attrs?: Attrs): SVGElement
export function PhonePause(attrs?: Attrs): SVGElement
export function TextColumns(attrs?: Attrs): SVGElement
export function Copy(attrs?: Attrs): SVGElement
export function TextAlignCenter(attrs?: Attrs): SVGElement
export function BookmarksSimple(attrs?: Attrs): SVGElement
export function Detective(attrs?: Attrs): SVGElement
export function NumberThree(attrs?: Attrs): SVGElement
export function Bell(attrs?: Attrs): SVGElement
export function Octagon(attrs?: Attrs): SVGElement
export function HandSoap(attrs?: Attrs): SVGElement
export function FireSimple(attrs?: Attrs): SVGElement
export function Tooth(attrs?: Attrs): SVGElement
export function BoxingGlove(attrs?: Attrs): SVGElement
export function Chat(attrs?: Attrs): SVGElement
export function Island(attrs?: Attrs): SVGElement
export function ArrowElbowDownRight(attrs?: Attrs): SVGElement
export function BatteryWarning(attrs?: Attrs): SVGElement
export function HandPalm(attrs?: Attrs): SVGElement
export function TreeStructure(attrs?: Attrs): SVGElement
export function ListDashes(attrs?: Attrs): SVGElement
export function EjectSimple(attrs?: Attrs): SVGElement
export function ArrowBendRightUp(attrs?: Attrs): SVGElement
export function Gradient(attrs?: Attrs): SVGElement
export function Repeat(attrs?: Attrs): SVGElement
export function TextAlignJustify(attrs?: Attrs): SVGElement
export function SpeakerX(attrs?: Attrs): SVGElement
export function Divide(attrs?: Attrs): SVGElement
export function SpeakerSimpleLow(attrs?: Attrs): SVGElement
export function Files(attrs?: Attrs): SVGElement
export function LineVertical(attrs?: Attrs): SVGElement
export function SkipBackCircle(attrs?: Attrs): SVGElement
export function Copyleft(attrs?: Attrs): SVGElement
export function Club(attrs?: Attrs): SVGElement
export function SubsetOf(attrs?: Attrs): SVGElement
export function UserCircleDashed(attrs?: Attrs): SVGElement
export function ClockCounterClockwise(attrs?: Attrs): SVGElement
export function AddressBook(attrs?: Attrs): SVGElement
export function Tornado(attrs?: Attrs): SVGElement
export function File(attrs?: Attrs): SVGElement
export function Control(attrs?: Attrs): SVGElement
export function CaretLeft(attrs?: Attrs): SVGElement
export function Motorcycle(attrs?: Attrs): SVGElement
export function TreasureChest(attrs?: Attrs): SVGElement
export function WarningOctagon(attrs?: Attrs): SVGElement
export function UserList(attrs?: Attrs): SVGElement
export function CalendarBlank(attrs?: Attrs): SVGElement
export function Onigiri(attrs?: Attrs): SVGElement
export function Cat(attrs?: Attrs): SVGElement
export function HandDeposit(attrs?: Attrs): SVGElement
export function ArrowsLeftRight(attrs?: Attrs): SVGElement
export function CameraSlash(attrs?: Attrs): SVGElement
export function HandbagSimple(attrs?: Attrs): SVGElement
export function CloudSnow(attrs?: Attrs): SVGElement
export function FilmScript(attrs?: Attrs): SVGElement
export function Popcorn(attrs?: Attrs): SVGElement
export function ThumbsDown(attrs?: Attrs): SVGElement
export function Windmill(attrs?: Attrs): SVGElement
export function Crane(attrs?: Attrs): SVGElement
export function DiscoBall(attrs?: Attrs): SVGElement
export function DownloadSimple(attrs?: Attrs): SVGElement
export function TennisBall(attrs?: Attrs): SVGElement
export function Cake(attrs?: Attrs): SVGElement
export function ShuffleAngular(attrs?: Attrs): SVGElement
export function PaintBrushHousehold(attrs?: Attrs): SVGElement
export function House(attrs?: Attrs): SVGElement
export function ArrowUpRight(attrs?: Attrs): SVGElement
export function Stethoscope(attrs?: Attrs): SVGElement
export function LinkBreak(attrs?: Attrs): SVGElement
export function Upload(attrs?: Attrs): SVGElement
export function StarFour(attrs?: Attrs): SVGElement
export function Record(attrs?: Attrs): SVGElement
export function Thermometer(attrs?: Attrs): SVGElement
export function Waveform(attrs?: Attrs): SVGElement
export function Synagogue(attrs?: Attrs): SVGElement
export function NumberSquareZero(attrs?: Attrs): SVGElement
export function SupersetProperOf(attrs?: Attrs): SVGElement
export function Scribble(attrs?: Attrs): SVGElement
export function TrafficSignal(attrs?: Attrs): SVGElement
export function FileArchive(attrs?: Attrs): SVGElement
export function CurrencyGbp(attrs?: Attrs): SVGElement
export function FileMd(attrs?: Attrs): SVGElement
export function HeartStraightBreak(attrs?: Attrs): SVGElement
export function Basket(attrs?: Attrs): SVGElement
export function HourglassSimpleHigh(attrs?: Attrs): SVGElement
export function ThermometerSimple(attrs?: Attrs): SVGElement
export function Bridge(attrs?: Attrs): SVGElement
export function Baby(attrs?: Attrs): SVGElement
export function FileHtml(attrs?: Attrs): SVGElement
export function Key(attrs?: Attrs): SVGElement
export function Toilet(attrs?: Attrs): SVGElement
export function Calculator(attrs?: Attrs): SVGElement
export function FunnelSimple(attrs?: Attrs): SVGElement
export function Leaf(attrs?: Attrs): SVGElement
export function EnvelopeSimple(attrs?: Attrs): SVGElement
export function SpeakerNone(attrs?: Attrs): SVGElement
export function ArrowCircleRight(attrs?: Attrs): SVGElement
export function PicnicTable(attrs?: Attrs): SVGElement
export function FileXls(attrs?: Attrs): SVGElement
export function ShieldChevron(attrs?: Attrs): SVGElement
export function BellSimple(attrs?: Attrs): SVGElement
export function BluetoothConnected(attrs?: Attrs): SVGElement
export function Prohibit(attrs?: Attrs): SVGElement
export function FolderUser(attrs?: Attrs): SVGElement
export function PaintBucket(attrs?: Attrs): SVGElement
export function SkipForward(attrs?: Attrs): SVGElement
export function Globe(attrs?: Attrs): SVGElement
export function ShieldCheckered(attrs?: Attrs): SVGElement
export function Pentagram(attrs?: Attrs): SVGElement
export function Shapes(attrs?: Attrs): SVGElement
export function Queue(attrs?: Attrs): SVGElement
export function HairDryer(attrs?: Attrs): SVGElement
export function Cricket(attrs?: Attrs): SVGElement
export function GlobeSimple(attrs?: Attrs): SVGElement
export function ArrowUUpLeft(attrs?: Attrs): SVGElement
export function Shield(attrs?: Attrs): SVGElement
export function MonitorArrowUp(attrs?: Attrs): SVGElement
export function NotMemberOf(attrs?: Attrs): SVGElement
export function Strategy(attrs?: Attrs): SVGElement
export function Airplay(attrs?: Attrs): SVGElement
export function Mouse(attrs?: Attrs): SVGElement
export function Backpack(attrs?: Attrs): SVGElement
export function LineSegment(attrs?: Attrs): SVGElement
export function Lectern(attrs?: Attrs): SVGElement
export function ShieldSlash(attrs?: Attrs): SVGElement
export function CoinVertical(attrs?: Attrs): SVGElement
export function PaperPlaneTilt(attrs?: Attrs): SVGElement
export function PhoneX(attrs?: Attrs): SVGElement
export function Perspective(attrs?: Attrs): SVGElement
export function CastleTurret(attrs?: Attrs): SVGElement
export function Lockers(attrs?: Attrs): SVGElement
export function WebhooksLogo(attrs?: Attrs): SVGElement
export function Handbag(attrs?: Attrs): SVGElement
export function CurrencyDollar(attrs?: Attrs): SVGElement
export function AirplaneInFlight(attrs?: Attrs): SVGElement
export function Notebook(attrs?: Attrs): SVGElement
export function ChartLineDown(attrs?: Attrs): SVGElement
export function AlignCenterVerticalSimple(attrs?: Attrs): SVGElement
export function HandEye(attrs?: Attrs): SVGElement
export function SpinnerGap(attrs?: Attrs): SVGElement
export function Radio(attrs?: Attrs): SVGElement
export function Pi(attrs?: Attrs): SVGElement
export function ArrowElbowLeftDown(attrs?: Attrs): SVGElement
export function WifiNone(attrs?: Attrs): SVGElement
export function HandTap(attrs?: Attrs): SVGElement
export function CurrencyJpy(attrs?: Attrs): SVGElement
export function Highlighter(attrs?: Attrs): SVGElement
export function Biohazard(attrs?: Attrs): SVGElement
export function FootballHelmet(attrs?: Attrs): SVGElement
export function ArrowLineDown(attrs?: Attrs): SVGElement
export function HardDrives(attrs?: Attrs): SVGElement
export function Horse(attrs?: Attrs): SVGElement
export function DeviceRotate(attrs?: Attrs): SVGElement
export function CaretDoubleDown(attrs?: Attrs): SVGElement
export function Cube(attrs?: Attrs): SVGElement
export function FilePy(attrs?: Attrs): SVGElement
export function GearSix(attrs?: Attrs): SVGElement
export function CloudCheck(attrs?: Attrs): SVGElement
export function NumberSquareSeven(attrs?: Attrs): SVGElement
export function SwimmingPool(attrs?: Attrs): SVGElement
export function ClipboardText(attrs?: Attrs): SVGElement
export function PencilSimple(attrs?: Attrs): SVGElement
export function GoogleChromeLogo(attrs?: Attrs): SVGElement
export function PushPinSimpleSlash(attrs?: Attrs): SVGElement
export function Vibrate(attrs?: Attrs): SVGElement
export function LockKeyOpen(attrs?: Attrs): SVGElement
export function BellRinging(attrs?: Attrs): SVGElement
export function Megaphone(attrs?: Attrs): SVGElement
export function FlagBanner(attrs?: Attrs): SVGElement
export function IceCream(attrs?: Attrs): SVGElement
export function NewspaperClipping(attrs?: Attrs): SVGElement
export function DiceFour(attrs?: Attrs): SVGElement
export function GoogleCardboardLogo(attrs?: Attrs): SVGElement
export function CornersOut(attrs?: Attrs): SVGElement
export function StopCircle(attrs?: Attrs): SVGElement
export function OpenAiLogo(attrs?: Attrs): SVGElement
export function Hockey(attrs?: Attrs): SVGElement
export function Gauge(attrs?: Attrs): SVGElement
export function Power(attrs?: Attrs): SVGElement
export function CheckSquareOffset(attrs?: Attrs): SVGElement
export function Joystick(attrs?: Attrs): SVGElement
export function VectorThree(attrs?: Attrs): SVGElement
export function Hamburger(attrs?: Attrs): SVGElement
export function Hand(attrs?: Attrs): SVGElement
export function VectorTwo(attrs?: Attrs): SVGElement
export function CaretRight(attrs?: Attrs): SVGElement
export function MicrosoftWordLogo(attrs?: Attrs): SVGElement
export function UserCheck(attrs?: Attrs): SVGElement
export function SpeakerSimpleX(attrs?: Attrs): SVGElement
export function HardHat(attrs?: Attrs): SVGElement
export function FileCss(attrs?: Attrs): SVGElement
export function Jar(attrs?: Attrs): SVGElement
export function ArrowElbowLeftUp(attrs?: Attrs): SVGElement
export function Tractor(attrs?: Attrs): SVGElement
export function ArrowLineLeft(attrs?: Attrs): SVGElement
export function PianoKeys(attrs?: Attrs): SVGElement
export function DevToLogo(attrs?: Attrs): SVGElement
export function DotsThreeVertical(attrs?: Attrs): SVGElement
export function Gps(attrs?: Attrs): SVGElement
export function AlignCenterVertical(attrs?: Attrs): SVGElement
export function Gif(attrs?: Attrs): SVGElement
export function Cardholder(attrs?: Attrs): SVGElement
export function Sliders(attrs?: Attrs): SVGElement
export function Alien(attrs?: Attrs): SVGElement
export function CaretDoubleLeft(attrs?: Attrs): SVGElement
export function SpeakerSimpleHigh(attrs?: Attrs): SVGElement
export function SmileyNervous(attrs?: Attrs): SVGElement
export function FolderDashed(attrs?: Attrs): SVGElement
export function FileMinus(attrs?: Attrs): SVGElement
export function Calendar(attrs?: Attrs): SVGElement
export function WindowsLogo(attrs?: Attrs): SVGElement
export function ArrowLineDownRight(attrs?: Attrs): SVGElement
export function CurrencyKzt(attrs?: Attrs): SVGElement
export function TextItalic(attrs?: Attrs): SVGElement
export function EnvelopeSimpleOpen(attrs?: Attrs): SVGElement
export function Screencast(attrs?: Attrs): SVGElement
export function RowsPlusTop(attrs?: Attrs): SVGElement
export function BellZ(attrs?: Attrs): SVGElement
export function FileTsx(attrs?: Attrs): SVGElement
export function Notepad(attrs?: Attrs): SVGElement
export function FlagPennant(attrs?: Attrs): SVGElement
export function TextH(attrs?: Attrs): SVGElement
export function Blueprint(attrs?: Attrs): SVGElement
export function GitCommit(attrs?: Attrs): SVGElement
export function Flashlight(attrs?: Attrs): SVGElement
export function Rectangle(attrs?: Attrs): SVGElement
export function Orange(attrs?: Attrs): SVGElement
export function CloudX(attrs?: Attrs): SVGElement
export function ToggleLeft(attrs?: Attrs): SVGElement
export function Planet(attrs?: Attrs): SVGElement
export function GoogleDriveLogo(attrs?: Attrs): SVGElement
export function ContactlessPayment(attrs?: Attrs): SVGElement
export function Palette(attrs?: Attrs): SVGElement
export function CaretDoubleRight(attrs?: Attrs): SVGElement
export function Grains(attrs?: Attrs): SVGElement
export function TextHThree(attrs?: Attrs): SVGElement
export function ChartScatter(attrs?: Attrs): SVGElement
export function SmileySad(attrs?: Attrs): SVGElement
export function Function(attrs?: Attrs): SVGElement
export function BookOpen(attrs?: Attrs): SVGElement
export function BatteryCharging(attrs?: Attrs): SVGElement
export function Flame(attrs?: Attrs): SVGElement
export function LockSimple(attrs?: Attrs): SVGElement
export function ArrowSquareUpRight(attrs?: Attrs): SVGElement
export function Hash(attrs?: Attrs): SVGElement
export function SpeakerHifi(attrs?: Attrs): SVGElement
export function BaseballCap(attrs?: Attrs): SVGElement
export function Plus(attrs?: Attrs): SVGElement
export function Football(attrs?: Attrs): SVGElement
export function SpotifyLogo(attrs?: Attrs): SVGElement
export function Toolbox(attrs?: Attrs): SVGElement
export function Export(attrs?: Attrs): SVGElement
export function BoxArrowUp(attrs?: Attrs): SVGElement
export function CubeFocus(attrs?: Attrs): SVGElement
export function FloppyDisk(attrs?: Attrs): SVGElement
export function FileCSharp(attrs?: Attrs): SVGElement
export function CurrencyCircleDollar(attrs?: Attrs): SVGElement
export function ArrowsOut(attrs?: Attrs): SVGElement
export function SprayBottle(attrs?: Attrs): SVGElement
export function NumberZero(attrs?: Attrs): SVGElement
export function GenderNonbinary(attrs?: Attrs): SVGElement
export function Bulldozer(attrs?: Attrs): SVGElement
export function ArrowBendDownRight(attrs?: Attrs): SVGElement
export function BellSimpleZ(attrs?: Attrs): SVGElement
export function CompassTool(attrs?: Attrs): SVGElement
export function ThermometerCold(attrs?: Attrs): SVGElement
export function AsteriskSimple(attrs?: Attrs): SVGElement
export function ArticleNyTimes(attrs?: Attrs): SVGElement
export function Pipe(attrs?: Attrs): SVGElement
export function LineSegments(attrs?: Attrs): SVGElement
export function AlignLeft(attrs?: Attrs): SVGElement
export function AppStoreLogo(attrs?: Attrs): SVGElement
export function PushPin(attrs?: Attrs): SVGElement
export function AnchorSimple(attrs?: Attrs): SVGElement
export function TwitterLogo(attrs?: Attrs): SVGElement
export function CornersIn(attrs?: Attrs): SVGElement
export function MinusSquare(attrs?: Attrs): SVGElement
export function FilePpt(attrs?: Attrs): SVGElement
export function ArrowFatUp(attrs?: Attrs): SVGElement
export function Password(attrs?: Attrs): SVGElement
export function OfficeChair(attrs?: Attrs): SVGElement
export function Browser(attrs?: Attrs): SVGElement
export function ThreadsLogo(attrs?: Attrs): SVGElement
export function Bluetooth(attrs?: Attrs): SVGElement
export function DeviceMobileCamera(attrs?: Attrs): SVGElement
export function BugBeetle(attrs?: Attrs): SVGElement
export function JarLabel(attrs?: Attrs): SVGElement
export function VinylRecord(attrs?: Attrs): SVGElement
export function BatteryPlusVertical(attrs?: Attrs): SVGElement
export function ExcludeSquare(attrs?: Attrs): SVGElement
export function MicrosoftTeamsLogo(attrs?: Attrs): SVGElement
export function FolderSimpleDashed(attrs?: Attrs): SVGElement
export function ListNumbers(attrs?: Attrs): SVGElement
export function Notches(attrs?: Attrs): SVGElement
export function Signature(attrs?: Attrs): SVGElement
export function ChartBarHorizontal(attrs?: Attrs): SVGElement
export function ArrowArcLeft(attrs?: Attrs): SVGElement
export function PenNibStraight(attrs?: Attrs): SVGElement
export function CellSignalMedium(attrs?: Attrs): SVGElement
export function IntersectThree(attrs?: Attrs): SVGElement
export function ShoppingCartSimple(attrs?: Attrs): SVGElement
export function ArrowsInCardinal(attrs?: Attrs): SVGElement
export function GlobeSimpleX(attrs?: Attrs): SVGElement
export function ChargingStation(attrs?: Attrs): SVGElement
export function CalendarX(attrs?: Attrs): SVGElement
export function SmileyBlank(attrs?: Attrs): SVGElement
export function BuildingApartment(attrs?: Attrs): SVGElement
export function Pulse(attrs?: Attrs): SVGElement
export function Clock(attrs?: Attrs): SVGElement
export function SupersetOf(attrs?: Attrs): SVGElement
export function ChatSlash(attrs?: Attrs): SVGElement
export function At(attrs?: Attrs): SVGElement
export function CalendarDot(attrs?: Attrs): SVGElement
export function Buildings(attrs?: Attrs): SVGElement
export function BoundingBox(attrs?: Attrs): SVGElement
export function NumberOne(attrs?: Attrs): SVGElement
export function TrafficSign(attrs?: Attrs): SVGElement
export function FalloutShelter(attrs?: Attrs): SVGElement
export function Binary(attrs?: Attrs): SVGElement
export function MusicNoteSimple(attrs?: Attrs): SVGElement
export function DeviceMobileSlash(attrs?: Attrs): SVGElement
export function CarSimple(attrs?: Attrs): SVGElement
export function EyeSlash(attrs?: Attrs): SVGElement
export function MinusCircle(attrs?: Attrs): SVGElement
export function CopySimple(attrs?: Attrs): SVGElement
export function MapPin(attrs?: Attrs): SVGElement
export function FolderStar(attrs?: Attrs): SVGElement
export function Sidebar(attrs?: Attrs): SVGElement
export function Selection(attrs?: Attrs): SVGElement
export function AlignRightSimple(attrs?: Attrs): SVGElement
export function NumberSix(attrs?: Attrs): SVGElement
export function Paragraph(attrs?: Attrs): SVGElement
export function SlidersHorizontal(attrs?: Attrs): SVGElement
export function GenderMale(attrs?: Attrs): SVGElement
export function ChefHat(attrs?: Attrs): SVGElement
export function CashRegister(attrs?: Attrs): SVGElement
export function Log(attrs?: Attrs): SVGElement
export function Acorn(attrs?: Attrs): SVGElement
export function BracketsSquare(attrs?: Attrs): SVGElement
export function MicrosoftOutlookLogo(attrs?: Attrs): SVGElement
export function NyTimesLogo(attrs?: Attrs): SVGElement
export function Yarn(attrs?: Attrs): SVGElement
export function TruckTrailer(attrs?: Attrs): SVGElement
export function CableCar(attrs?: Attrs): SVGElement
export function MapPinPlus(attrs?: Attrs): SVGElement
export function FilmStrip(attrs?: Attrs): SVGElement
export function BatteryEmpty(attrs?: Attrs): SVGElement
export function FolderLock(attrs?: Attrs): SVGElement
export function HandPointing(attrs?: Attrs): SVGElement
export function SkipBack(attrs?: Attrs): SVGElement
export function NumberCircleSix(attrs?: Attrs): SVGElement
export function Dot(attrs?: Attrs): SVGElement
export function ThumbsUp(attrs?: Attrs): SVGElement
export function CloudRain(attrs?: Attrs): SVGElement
export function UserSquare(attrs?: Attrs): SVGElement
export function Bag(attrs?: Attrs): SVGElement
export function FlipVertical(attrs?: Attrs): SVGElement
export function Ambulance(attrs?: Attrs): SVGElement
export function DiscordLogo(attrs?: Attrs): SVGElement
export function Images(attrs?: Attrs): SVGElement
export function AlignLeftSimple(attrs?: Attrs): SVGElement
export function NumberSeven(attrs?: Attrs): SVGElement
export function ApplePodcastsLogo(attrs?: Attrs): SVGElement
export function NumberCircleEight(attrs?: Attrs): SVGElement
export function BellSimpleRinging(attrs?: Attrs): SVGElement
export function BatteryPlus(attrs?: Attrs): SVGElement
export function Database(attrs?: Attrs): SVGElement
export function NumberFour(attrs?: Attrs): SVGElement
export function PlugCharging(attrs?: Attrs): SVGElement
export function ArrowCircleUp(attrs?: Attrs): SVGElement
export function MaskHappy(attrs?: Attrs): SVGElement
export function Wind(attrs?: Attrs): SVGElement
export function Medal(attrs?: Attrs): SVGElement
export function FireTruck(attrs?: Attrs): SVGElement
export function ArrowURightDown(attrs?: Attrs): SVGElement
export function IdentificationCard(attrs?: Attrs): SVGElement
export function CurrencyEur(attrs?: Attrs): SVGElement
export function ApproximateEquals(attrs?: Attrs): SVGElement
export function Egg(attrs?: Attrs): SVGElement
export function Speedometer(attrs?: Attrs): SVGElement
export function ArrowsInSimple(attrs?: Attrs): SVGElement
export function NumberCircleOne(attrs?: Attrs): SVGElement
export function SignOut(attrs?: Attrs): SVGElement
export function Jeep(attrs?: Attrs): SVGElement
export function Sigma(attrs?: Attrs): SVGElement
export function TidalLogo(attrs?: Attrs): SVGElement
export function PlusCircle(attrs?: Attrs): SVGElement
export function Faders(attrs?: Attrs): SVGElement
export function FilmSlate(attrs?: Attrs): SVGElement
export function VideoCameraSlash(attrs?: Attrs): SVGElement
export function MarkdownLogo(attrs?: Attrs): SVGElement
export function Storefront(attrs?: Attrs): SVGElement
export function PresentationChart(attrs?: Attrs): SVGElement
export function Tram(attrs?: Attrs): SVGElement
export function BookmarkSimple(attrs?: Attrs): SVGElement
export function NavigationArrow(attrs?: Attrs): SVGElement
export function Envelope(attrs?: Attrs): SVGElement
export function BatteryHigh(attrs?: Attrs): SVGElement
export function Pentagon(attrs?: Attrs): SVGElement
export function UserPlus(attrs?: Attrs): SVGElement
export function Lightbulb(attrs?: Attrs): SVGElement
export function Broom(attrs?: Attrs): SVGElement
export function XSquare(attrs?: Attrs): SVGElement
export function PersonSimpleBike(attrs?: Attrs): SVGElement
export function SuitcaseSimple(attrs?: Attrs): SVGElement
export function Tree(attrs?: Attrs): SVGElement
export function ArrowFatLinesRight(attrs?: Attrs): SVGElement
export function Spinner(attrs?: Attrs): SVGElement
export function ArrowCounterClockwise(attrs?: Attrs): SVGElement
export function DeviceMobileSpeaker(attrs?: Attrs): SVGElement
export function TextTSlash(attrs?: Attrs): SVGElement
export function Aperture(attrs?: Attrs): SVGElement
export function Couch(attrs?: Attrs): SVGElement
export function TextHOne(attrs?: Attrs): SVGElement
export function Sparkle(attrs?: Attrs): SVGElement
export function SmileyWink(attrs?: Attrs): SVGElement
export function ArrowsOutLineVertical(attrs?: Attrs): SVGElement
export function Drone(attrs?: Attrs): SVGElement
export function UserCircle(attrs?: Attrs): SVGElement
export function Eraser(attrs?: Attrs): SVGElement
export function Fish(attrs?: Attrs): SVGElement
export function DotsThreeOutline(attrs?: Attrs): SVGElement
export function NetworkSlash(attrs?: Attrs): SVGElement
export function GridNine(attrs?: Attrs): SVGElement
export function CloudSlash(attrs?: Attrs): SVGElement
export function UserCirclePlus(attrs?: Attrs): SVGElement
export function BluetoothSlash(attrs?: Attrs): SVGElement
export function RepeatOnce(attrs?: Attrs): SVGElement
export function TextHSix(attrs?: Attrs): SVGElement
export function Moon(attrs?: Attrs): SVGElement
export function FlagBannerFold(attrs?: Attrs): SVGElement
export function ArrowsVertical(attrs?: Attrs): SVGElement
export function ShieldCheck(attrs?: Attrs): SVGElement
export function DoorOpen(attrs?: Attrs): SVGElement
export function ColumnsPlusLeft(attrs?: Attrs): SVGElement
export function ImageSquare(attrs?: Attrs): SVGElement
export function PlusSquare(attrs?: Attrs): SVGElement
export function AndroidLogo(attrs?: Attrs): SVGElement
export function SubsetProperOf(attrs?: Attrs): SVGElement
export function Van(attrs?: Attrs): SVGElement
export function PhosphorLogo(attrs?: Attrs): SVGElement
export function FileVideo(attrs?: Attrs): SVGElement
export function NumberSquareTwo(attrs?: Attrs): SVGElement
export function XCircle(attrs?: Attrs): SVGElement
export function CloudSun(attrs?: Attrs): SVGElement
export function SelectionSlash(attrs?: Attrs): SVGElement
export function RectangleDashed(attrs?: Attrs): SVGElement
export function FishSimple(attrs?: Attrs): SVGElement
export function CellSignalX(attrs?: Attrs): SVGElement
export function BabyCarriage(attrs?: Attrs): SVGElement
export function Car(attrs?: Attrs): SVGElement
export function FlyingSaucer(attrs?: Attrs): SVGElement
export function Swatches(attrs?: Attrs): SVGElement
export function Share(attrs?: Attrs): SVGElement
export function SmileySticker(attrs?: Attrs): SVGElement
export function Crosshair(attrs?: Attrs): SVGElement
export function WaveTriangle(attrs?: Attrs): SVGElement
export function DotsSixVertical(attrs?: Attrs): SVGElement
export function MoneyWavy(attrs?: Attrs): SVGElement
export function X(attrs?: Attrs): SVGElement
export function CaretCircleLeft(attrs?: Attrs): SVGElement
export function ClosedCaptioning(attrs?: Attrs): SVGElement
export function XLogo(attrs?: Attrs): SVGElement
export function Metronome(attrs?: Attrs): SVGElement
export function GpsSlash(attrs?: Attrs): SVGElement
export function MagnetStraight(attrs?: Attrs): SVGElement
export function BatteryVerticalHigh(attrs?: Attrs): SVGElement
export function WaveSine(attrs?: Attrs): SVGElement
export function ArrowUUpRight(attrs?: Attrs): SVGElement
export function Bus(attrs?: Attrs): SVGElement
export function BluetoothX(attrs?: Attrs): SVGElement
export function Binoculars(attrs?: Attrs): SVGElement
export function MagnifyingGlassMinus(attrs?: Attrs): SVGElement
export function SpeakerHigh(attrs?: Attrs): SVGElement
export function ArrowDown(attrs?: Attrs): SVGElement
export function Lock(attrs?: Attrs): SVGElement
export function BowlFood(attrs?: Attrs): SVGElement
export function ArrowsIn(attrs?: Attrs): SVGElement
export function MouseRightClick(attrs?: Attrs): SVGElement
export function LinktreeLogo(attrs?: Attrs): SVGElement
export function Ladder(attrs?: Attrs): SVGElement
export function ClockCountdown(attrs?: Attrs): SVGElement
export function Playlist(attrs?: Attrs): SVGElement
export function BellSimpleSlash(attrs?: Attrs): SVGElement
export function UserMinus(attrs?: Attrs): SVGElement
export function Mountains(attrs?: Attrs): SVGElement
export function FileJs(attrs?: Attrs): SVGElement
export function DotsThreeCircleVertical(attrs?: Attrs): SVGElement
export function Slideshow(attrs?: Attrs): SVGElement
export function Farm(attrs?: Attrs): SVGElement
export function ArrowsOutCardinal(attrs?: Attrs): SVGElement
export function Seatbelt(attrs?: Attrs): SVGElement
export function TrademarkRegistered(attrs?: Attrs): SVGElement
export function CurrencyNgn(attrs?: Attrs): SVGElement
export function SidebarSimple(attrs?: Attrs): SVGElement
export function Nut(attrs?: Attrs): SVGElement
export function Presentation(attrs?: Attrs): SVGElement
export function ArrowElbowDownLeft(attrs?: Attrs): SVGElement
export function HashStraight(attrs?: Attrs): SVGElement
export function CellSignalSlash(attrs?: Attrs): SVGElement
export function BatteryLow(attrs?: Attrs): SVGElement
export function Armchair(attrs?: Attrs): SVGElement
export function ArrowBendUpLeft(attrs?: Attrs): SVGElement
export function TextSuperscript(attrs?: Attrs): SVGElement
export function ArrowSquareDownLeft(attrs?: Attrs): SVGElement
export function ChatTeardrop(attrs?: Attrs): SVGElement
export function ChartBar(attrs?: Attrs): SVGElement
export function CaretCircleDoubleDown(attrs?: Attrs): SVGElement
export function NumberCircleFour(attrs?: Attrs): SVGElement
export function Screwdriver(attrs?: Attrs): SVGElement
export function PixLogo(attrs?: Attrs): SVGElement
export function BaseballHelmet(attrs?: Attrs): SVGElement
export function CloudWarning(attrs?: Attrs): SVGElement
export function Belt(attrs?: Attrs): SVGElement
export function TextHFive(attrs?: Attrs): SVGElement
export function FilmReel(attrs?: Attrs): SVGElement
export function GraduationCap(attrs?: Attrs): SVGElement
export function SmileyMeh(attrs?: Attrs): SVGElement
export function WifiHigh(attrs?: Attrs): SVGElement
export function BowlingBall(attrs?: Attrs): SVGElement
export function BookUser(attrs?: Attrs): SVGElement
export function Layout(attrs?: Attrs): SVGElement
export function ArrowFatLineLeft(attrs?: Attrs): SVGElement
export function Wallet(attrs?: Attrs): SVGElement
export function ClockClockwise(attrs?: Attrs): SVGElement
export function SunHorizon(attrs?: Attrs): SVGElement
export function FacebookLogo(attrs?: Attrs): SVGElement
export function SkypeLogo(attrs?: Attrs): SVGElement
export function MessengerLogo(attrs?: Attrs): SVGElement
export function BracketsAngle(attrs?: Attrs): SVGElement
export function ShoppingCart(attrs?: Attrs): SVGElement
export function Devices(attrs?: Attrs): SVGElement
export function Lego(attrs?: Attrs): SVGElement
export function CurrencyBtc(attrs?: Attrs): SVGElement
export function HourglassHigh(attrs?: Attrs): SVGElement
export function AngularLogo(attrs?: Attrs): SVGElement
export function DeviceMobile(attrs?: Attrs): SVGElement
export function PersonSimpleCircle(attrs?: Attrs): SVGElement
export function Notification(attrs?: Attrs): SVGElement
export function FileCloud(attrs?: Attrs): SVGElement
export function PlayCircle(attrs?: Attrs): SVGElement
export function AddressBookTabs(attrs?: Attrs): SVGElement
export function FileMagnifyingGlass(attrs?: Attrs): SVGElement
export function MopedFront(attrs?: Attrs): SVGElement
export function Timer(attrs?: Attrs): SVGElement
export function ArrowsInLineHorizontal(attrs?: Attrs): SVGElement
export function NumberSquareThree(attrs?: Attrs): SVGElement
export function Tag(attrs?: Attrs): SVGElement
export function Graph(attrs?: Attrs): SVGElement
export function DotsThreeCircle(attrs?: Attrs): SVGElement
export function ArrowCircleUpLeft(attrs?: Attrs): SVGElement
export function CourtBasketball(attrs?: Attrs): SVGElement
export function Eyes(attrs?: Attrs): SVGElement
export function SoccerBall(attrs?: Attrs): SVGElement
export function Airplane(attrs?: Attrs): SVGElement
export function Goggles(attrs?: Attrs): SVGElement
export function PaintRoller(attrs?: Attrs): SVGElement
export function DotOutline(attrs?: Attrs): SVGElement
export function List(attrs?: Attrs): SVGElement
export function Waves(attrs?: Attrs): SVGElement
export function CaretCircleDoubleLeft(attrs?: Attrs): SVGElement
export function WhatsappLogo(attrs?: Attrs): SVGElement
export function Keyhole(attrs?: Attrs): SVGElement
export function SpeakerSimpleNone(attrs?: Attrs): SVGElement
export function Pause(attrs?: Attrs): SVGElement
export function ArrowLineUpLeft(attrs?: Attrs): SVGElement
export function Bicycle(attrs?: Attrs): SVGElement
export function AirplaneTakeoff(attrs?: Attrs): SVGElement
export function Popsicle(attrs?: Attrs): SVGElement
export function BellSlash(attrs?: Attrs): SVGElement
export function Seal(attrs?: Attrs): SVGElement
export function CirclesFour(attrs?: Attrs): SVGElement
export function PaintBrush(attrs?: Attrs): SVGElement
export function BoxArrowDown(attrs?: Attrs): SVGElement
export function WarningCircle(attrs?: Attrs): SVGElement
export function SketchLogo(attrs?: Attrs): SVGElement
export function EscalatorDown(attrs?: Attrs): SVGElement
export function FileSvg(attrs?: Attrs): SVGElement
export function WarningDiamond(attrs?: Attrs): SVGElement
export function GitMerge(attrs?: Attrs): SVGElement
export function ArrowFatLineDown(attrs?: Attrs): SVGElement
export function FadersHorizontal(attrs?: Attrs): SVGElement
export function Bookmarks(attrs?: Attrs): SVGElement
export function PokerChip(attrs?: Attrs): SVGElement
export function ReceiptX(attrs?: Attrs): SVGElement
export function ArrowElbowRightUp(attrs?: Attrs): SVGElement
export function TerminalWindow(attrs?: Attrs): SVGElement
export function GreaterThan(attrs?: Attrs): SVGElement
export function ThermometerHot(attrs?: Attrs): SVGElement
export function ArrowClockwise(attrs?: Attrs): SVGElement
export function PinterestLogo(attrs?: Attrs): SVGElement
export function CarProfile(attrs?: Attrs): SVGElement
export function FolderOpen(attrs?: Attrs): SVGElement
export function ArrowDownRight(attrs?: Attrs): SVGElement
export function CrownCross(attrs?: Attrs): SVGElement
export function RainbowCloud(attrs?: Attrs): SVGElement
export function PlugsConnected(attrs?: Attrs): SVGElement
export function FlowArrow(attrs?: Attrs): SVGElement
export function FileX(attrs?: Attrs): SVGElement
export function Parallelogram(attrs?: Attrs): SVGElement
export function GitDiff(attrs?: Attrs): SVGElement
export function Shovel(attrs?: Attrs): SVGElement
export function Coins(attrs?: Attrs): SVGElement
export function Feather(attrs?: Attrs): SVGElement
export function StackSimple(attrs?: Attrs): SVGElement
export function ChatTeardropSlash(attrs?: Attrs): SVGElement
export function PencilLine(attrs?: Attrs): SVGElement
export function Paperclip(attrs?: Attrs): SVGElement
export function TreeEvergreen(attrs?: Attrs): SVGElement
export function Microphone(attrs?: Attrs): SVGElement
export function Crown(attrs?: Attrs): SVGElement
export function Terminal(attrs?: Attrs): SVGElement
export function BatteryVerticalLow(attrs?: Attrs): SVGElement
export function ScribbleLoop(attrs?: Attrs): SVGElement
export function CaretCircleDown(attrs?: Attrs): SVGElement
export function MouseSimple(attrs?: Attrs): SVGElement
export function Path(attrs?: Attrs): SVGElement
export function NumberCircleZero(attrs?: Attrs): SVGElement
export function MusicNotes(attrs?: Attrs): SVGElement
export function Dress(attrs?: Attrs): SVGElement
export function DiamondsFour(attrs?: Attrs): SVGElement
export function LightningA(attrs?: Attrs): SVGElement
export function CloudFog(attrs?: Attrs): SVGElement
export function Skull(attrs?: Attrs): SVGElement
export function GenderFemale(attrs?: Attrs): SVGElement
export function FileImage(attrs?: Attrs): SVGElement
export function DotsSix(attrs?: Attrs): SVGElement
export function RocketLaunch(attrs?: Attrs): SVGElement
export function ArrowLeft(attrs?: Attrs): SVGElement
export function CursorText(attrs?: Attrs): SVGElement
export function ClockUser(attrs?: Attrs): SVGElement
export function Equals(attrs?: Attrs): SVGElement
export function Baseball(attrs?: Attrs): SVGElement
export function Swap(attrs?: Attrs): SVGElement
export function Users(attrs?: Attrs): SVGElement
export function Table(attrs?: Attrs): SVGElement
export function Stamp(attrs?: Attrs): SVGElement
export function Star(attrs?: Attrs): SVGElement
export function ChatText(attrs?: Attrs): SVGElement
export function Diamond(attrs?: Attrs): SVGElement
export function Bed(attrs?: Attrs): SVGElement
export function MoonStars(attrs?: Attrs): SVGElement
export function SealWarning(attrs?: Attrs): SVGElement
export function ShoppingBag(attrs?: Attrs): SVGElement
export function Empty(attrs?: Attrs): SVGElement
export function GenderTransgender(attrs?: Attrs): SVGElement
export function CurrencyKrw(attrs?: Attrs): SVGElement
export function FinnTheHuman(attrs?: Attrs): SVGElement
export function HourglassSimpleLow(attrs?: Attrs): SVGElement
export function StripeLogo(attrs?: Attrs): SVGElement
export function HourglassLow(attrs?: Attrs): SVGElement
export function CoffeeBean(attrs?: Attrs): SVGElement
export function Siren(attrs?: Attrs): SVGElement
export function Hoodie(attrs?: Attrs): SVGElement
export function CurrencyEth(attrs?: Attrs): SVGElement
export function Boot(attrs?: Attrs): SVGElement
export function Door(attrs?: Attrs): SVGElement
export function CameraRotate(attrs?: Attrs): SVGElement
export function Watch(attrs?: Attrs): SVGElement
export function MusicNotesSimple(attrs?: Attrs): SVGElement
export function YoutubeLogo(attrs?: Attrs): SVGElement
export function ArrowULeftUp(attrs?: Attrs): SVGElement
export function LockKey(attrs?: Attrs): SVGElement
export function CirclesThree(attrs?: Attrs): SVGElement
export function Student(attrs?: Attrs): SVGElement
export function Ruler(attrs?: Attrs): SVGElement
export function ColumnsPlusRight(attrs?: Attrs): SVGElement
export function SealQuestion(attrs?: Attrs): SVGElement
export function Infinity(attrs?: Attrs): SVGElement
export function Usb(attrs?: Attrs): SVGElement
export function PersonSimpleSnowboard(attrs?: Attrs): SVGElement
export function CrownSimple(attrs?: Attrs): SVGElement
export function MegaphoneSimple(attrs?: Attrs): SVGElement
export function ArrowFatLineUp(attrs?: Attrs): SVGElement
export function Books(attrs?: Attrs): SVGElement
export function HandSwipeRight(attrs?: Attrs): SVGElement
export function TelevisionSimple(attrs?: Attrs): SVGElement
export function CloudLightning(attrs?: Attrs): SVGElement
export function StarOfDavid(attrs?: Attrs): SVGElement
export function ArrowBendDoubleUpRight(attrs?: Attrs): SVGElement
export function GooglePhotosLogo(attrs?: Attrs): SVGElement
export function FilePlus(attrs?: Attrs): SVGElement
export function Dna(attrs?: Attrs): SVGElement
export function RedditLogo(attrs?: Attrs): SVGElement
export function CreditCard(attrs?: Attrs): SVGElement
export function ArrowFatLinesDown(attrs?: Attrs): SVGElement
export function FileTs(attrs?: Attrs): SVGElement
export function GpsFix(attrs?: Attrs): SVGElement
export function Bone(attrs?: Attrs): SVGElement
export function DotsThree(attrs?: Attrs): SVGElement
export function ShoppingBagOpen(attrs?: Attrs): SVGElement
export function Printer(attrs?: Attrs): SVGElement
export function SoundcloudLogo(attrs?: Attrs): SVGElement
export function FramerLogo(attrs?: Attrs): SVGElement
export function PersonSimpleRun(attrs?: Attrs): SVGElement
export function StarAndCrescent(attrs?: Attrs): SVGElement
export function ShieldStar(attrs?: Attrs): SVGElement
export function Heartbeat(attrs?: Attrs): SVGElement
export function Sword(attrs?: Attrs): SVGElement
export function FourK(attrs?: Attrs): SVGElement
export function Intersection(attrs?: Attrs): SVGElement
export function Stack(attrs?: Attrs): SVGElement
export function LinkSimpleHorizontal(attrs?: Attrs): SVGElement
export function DiceThree(attrs?: Attrs): SVGElement
export function BeachBall(attrs?: Attrs): SVGElement
export function ShareNetwork(attrs?: Attrs): SVGElement
export function Pencil(attrs?: Attrs): SVGElement
export function LightningSlash(attrs?: Attrs): SVGElement
export function AirplaneTaxiing(attrs?: Attrs): SVGElement
export function NotEquals(attrs?: Attrs): SVGElement
export function DiceFive(attrs?: Attrs): SVGElement
export function Axe(attrs?: Attrs): SVGElement
export function HandWaving(attrs?: Attrs): SVGElement
export function Eyeglasses(attrs?: Attrs): SVGElement
export function Article(attrs?: Attrs): SVGElement
export function Polygon(attrs?: Attrs): SVGElement
export function Flask(attrs?: Attrs): SVGElement
export function SelectionBackground(attrs?: Attrs): SVGElement
export function Scooter(attrs?: Attrs): SVGElement
export function Hourglass(attrs?: Attrs): SVGElement
export function ChatsTeardrop(attrs?: Attrs): SVGElement
export function HandHeart(attrs?: Attrs): SVGElement
export function LockOpen(attrs?: Attrs): SVGElement
export function PaperPlane(attrs?: Attrs): SVGElement
export function PersonSimple(attrs?: Attrs): SVGElement
export function Question(attrs?: Attrs): SVGElement
export function HouseSimple(attrs?: Attrs): SVGElement
export function GlobeHemisphereEast(attrs?: Attrs): SVGElement
export function WifiX(attrs?: Attrs): SVGElement
export function CubeTransparent(attrs?: Attrs): SVGElement
export function BugDroid(attrs?: Attrs): SVGElement
export function Scales(attrs?: Attrs): SVGElement
export function BracketsRound(attrs?: Attrs): SVGElement
export function TrayArrowDown(attrs?: Attrs): SVGElement
export function ArrowElbowUpLeft(attrs?: Attrs): SVGElement
export function PlayPause(attrs?: Attrs): SVGElement
export function LightbulbFilament(attrs?: Attrs): SVGElement
export function Textbox(attrs?: Attrs): SVGElement
export function ArrowElbowLeft(attrs?: Attrs): SVGElement
export function Basketball(attrs?: Attrs): SVGElement
export function SelectionForeground(attrs?: Attrs): SVGElement
export function ChatCircleText(attrs?: Attrs): SVGElement
export function Triangle(attrs?: Attrs): SVGElement
export function Square(attrs?: Attrs): SVGElement
export function FileSql(attrs?: Attrs): SVGElement
export function ChartLineUp(attrs?: Attrs): SVGElement
export function Dresser(attrs?: Attrs): SVGElement
export function MemberOf(attrs?: Attrs): SVGElement
export function UserGear(attrs?: Attrs): SVGElement
export function AlignCenterHorizontalSimple(attrs?: Attrs): SVGElement
export function CheckSquare(attrs?: Attrs): SVGElement
export function RewindCircle(attrs?: Attrs): SVGElement
export function CursorClick(attrs?: Attrs): SVGElement
export function NotSupersetOf(attrs?: Attrs): SVGElement
export function Robot(attrs?: Attrs): SVGElement
export function CalendarStar(attrs?: Attrs): SVGElement
export function CellSignalHigh(attrs?: Attrs): SVGElement
export function GridFour(attrs?: Attrs): SVGElement
export function Cow(attrs?: Attrs): SVGElement
export function LockLaminatedOpen(attrs?: Attrs): SVGElement
export function Quotes(attrs?: Attrs): SVGElement
export function HandsPraying(attrs?: Attrs): SVGElement
export function Gift(attrs?: Attrs): SVGElement
export function HighHeel(attrs?: Attrs): SVGElement
export function VideoCamera(attrs?: Attrs): SVGElement
export function CaretCircleRight(attrs?: Attrs): SVGElement
export function UsersFour(attrs?: Attrs): SVGElement
export function ArrowRight(attrs?: Attrs): SVGElement
export function Pants(attrs?: Attrs): SVGElement
export function NumberSquareEight(attrs?: Attrs): SVGElement
export function ComputerTower(attrs?: Attrs): SVGElement
export function Cursor(attrs?: Attrs): SVGElement
export function Shower(attrs?: Attrs): SVGElement
export function Archive(attrs?: Attrs): SVGElement
export function UserCircleGear(attrs?: Attrs): SVGElement
export function Engine(attrs?: Attrs): SVGElement
export function Syringe(attrs?: Attrs): SVGElement
export function ChatCenteredSlash(attrs?: Attrs): SVGElement
export function CurrencyCny(attrs?: Attrs): SVGElement
export function SortAscending(attrs?: Attrs): SVGElement
export function ChartPieSlice(attrs?: Attrs): SVGElement
export function LinkedinLogo(attrs?: Attrs): SVGElement
export function GitFork(attrs?: Attrs): SVGElement
export function UploadSimple(attrs?: Attrs): SVGElement
export function Sun(attrs?: Attrs): SVGElement
export function FileTxt(attrs?: Attrs): SVGElement
export function Intersect(attrs?: Attrs): SVGElement
export function VirtualReality(attrs?: Attrs): SVGElement
export function TextStrikethrough(attrs?: Attrs): SVGElement
export function MicrophoneSlash(attrs?: Attrs): SVGElement
export function ReadCvLogo(attrs?: Attrs): SVGElement
export function GenderIntersex(attrs?: Attrs): SVGElement
export function Circle(attrs?: Attrs): SVGElement
export function PersonArmsSpread(attrs?: Attrs): SVGElement
export function GrainsSlash(attrs?: Attrs): SVGElement
export function ShareFat(attrs?: Attrs): SVGElement
export function CheckCircle(attrs?: Attrs): SVGElement
export function Oven(attrs?: Attrs): SVGElement
export function ArrowSquareDownRight(attrs?: Attrs): SVGElement
export function NumberNine(attrs?: Attrs): SVGElement
export function PauseCircle(attrs?: Attrs): SVGElement
export function ArrowsSplit(attrs?: Attrs): SVGElement
export function TextT(attrs?: Attrs): SVGElement
export function WifiMedium(attrs?: Attrs): SVGElement
export function SortDescending(attrs?: Attrs): SVGElement
export function Chalkboard(attrs?: Attrs): SVGElement
export function FileArrowDown(attrs?: Attrs): SVGElement
export function ArrowFatLinesLeft(attrs?: Attrs): SVGElement
export function Cigarette(attrs?: Attrs): SVGElement
export function SecurityCamera(attrs?: Attrs): SVGElement
export function MapPinSimpleLine(attrs?: Attrs): SVGElement
export function MagicWand(attrs?: Attrs): SVGElement
export function TreePalm(attrs?: Attrs): SVGElement
export function Stop(attrs?: Attrs): SVGElement
export function FirstAid(attrs?: Attrs): SVGElement
export function Broadcast(attrs?: Attrs): SVGElement
export function ImagesSquare(attrs?: Attrs): SVGElement
export function Crop(attrs?: Attrs): SVGElement
export function Atom(attrs?: Attrs): SVGElement
export function SelectionAll(attrs?: Attrs): SVGElement
export function LessThanOrEqual(attrs?: Attrs): SVGElement
export function FigmaLogo(attrs?: Attrs): SVGElement
export function ArrowBendUpRight(attrs?: Attrs): SVGElement
export function WebcamSlash(attrs?: Attrs): SVGElement
export function Moped(attrs?: Attrs): SVGElement
export function Rows(attrs?: Attrs): SVGElement
export function ArrowFatRight(attrs?: Attrs): SVGElement
export function ArrowBendLeftDown(attrs?: Attrs): SVGElement
export function LinkSimpleHorizontalBreak(attrs?: Attrs): SVGElement
export function ArrowUDownLeft(attrs?: Attrs): SVGElement
export function GoodreadsLogo(attrs?: Attrs): SVGElement
export function Pepper(attrs?: Attrs): SVGElement
export function MathOperations(attrs?: Attrs): SVGElement
export function Chats(attrs?: Attrs): SVGElement
export function NumberCircleThree(attrs?: Attrs): SVGElement
export function NumberCircleNine(attrs?: Attrs): SVGElement
export function ArrowsOutSimple(attrs?: Attrs): SVGElement
export function WifiLow(attrs?: Attrs): SVGElement
export function MapPinArea(attrs?: Attrs): SVGElement
export function FolderSimpleStar(attrs?: Attrs): SVGElement
export function Backspace(attrs?: Attrs): SVGElement
export function DropSimple(attrs?: Attrs): SVGElement
export function NotSubsetOf(attrs?: Attrs): SVGElement
export function UserFocus(attrs?: Attrs): SVGElement
export function Bread(attrs?: Attrs): SVGElement
export function CodeBlock(attrs?: Attrs): SVGElement
export function FileDoc(attrs?: Attrs): SVGElement
export function ScanSmiley(attrs?: Attrs): SVGElement
export function Lasso(attrs?: Attrs): SVGElement
export function Lifebuoy(attrs?: Attrs): SVGElement
export function Exam(attrs?: Attrs): SVGElement
export function Trademark(attrs?: Attrs): SVGElement
export function Warning(attrs?: Attrs): SVGElement
export function CellTower(attrs?: Attrs): SVGElement
export function Pen(attrs?: Attrs): SVGElement
export function Truck(attrs?: Attrs): SVGElement
export function VideoConference(attrs?: Attrs): SVGElement
export function QrCode(attrs?: Attrs): SVGElement
export function Folder(attrs?: Attrs): SVGElement
export function CaretCircleDoubleUp(attrs?: Attrs): SVGElement
export function Rabbit(attrs?: Attrs): SVGElement
export function HeadCircuit(attrs?: Attrs): SVGElement
export function MagnifyingGlassPlus(attrs?: Attrs): SVGElement
export function ArrowCircleLeft(attrs?: Attrs): SVGElement
export function ArrowBendDoubleUpLeft(attrs?: Attrs): SVGElement
export function Cross(attrs?: Attrs): SVGElement
export function AirplaneTilt(attrs?: Attrs): SVGElement
export function DiceSix(attrs?: Attrs): SVGElement
export function Desk(attrs?: Attrs): SVGElement
export function ProjectorScreenChart(attrs?: Attrs): SVGElement
export function WifiSlash(attrs?: Attrs): SVGElement
export function PhonePlus(attrs?: Attrs): SVGElement
export function Briefcase(attrs?: Attrs): SVGElement
export function Union(attrs?: Attrs): SVGElement
export function TrainSimple(attrs?: Attrs): SVGElement
export function Flag(attrs?: Attrs): SVGElement
export function ArrowBendRightDown(attrs?: Attrs): SVGElement
export function AirplaneLanding(attrs?: Attrs): SVGElement
export function ChalkboardSimple(attrs?: Attrs): SVGElement
export function SmileyMelting(attrs?: Attrs): SVGElement
export function DiceOne(attrs?: Attrs): SVGElement
export function ListPlus(attrs?: Attrs): SVGElement
export function Knife(attrs?: Attrs): SVGElement
export function ChatCircle(attrs?: Attrs): SVGElement
export function ShippingContainer(attrs?: Attrs): SVGElement
export function EyeClosed(attrs?: Attrs): SVGElement
export function TextAlignLeft(attrs?: Attrs): SVGElement
export function MarkerCircle(attrs?: Attrs): SVGElement
export function LetterCircleP(attrs?: Attrs): SVGElement
export function PaypalLogo(attrs?: Attrs): SVGElement
export function SmileyAngry(attrs?: Attrs): SVGElement
export function Stool(attrs?: Attrs): SVGElement
export function PersonSimpleSki(attrs?: Attrs): SVGElement
export function SquareLogo(attrs?: Attrs): SVGElement
export function Trolley(attrs?: Attrs): SVGElement
export function PaintBrushBroad(attrs?: Attrs): SVGElement
export function GearFine(attrs?: Attrs): SVGElement
export function Disc(attrs?: Attrs): SVGElement
export function Hammer(attrs?: Attrs): SVGElement
export function CaretCircleUp(attrs?: Attrs): SVGElement
export function TextSubscript(attrs?: Attrs): SVGElement
export function ArrowsMerge(attrs?: Attrs): SVGElement
export function Visor(attrs?: Attrs): SVGElement
export function ShirtFolded(attrs?: Attrs): SVGElement
export function ChatCenteredDots(attrs?: Attrs): SVGElement
export function FileVue(attrs?: Attrs): SVGElement
export function FlagCheckered(attrs?: Attrs): SVGElement
export function SimCard(attrs?: Attrs): SVGElement
export function StackOverflowLogo(attrs?: Attrs): SVGElement
export function CalendarCheck(attrs?: Attrs): SVGElement
export function SelectionInverse(attrs?: Attrs): SVGElement
export function NumberSquareFive(attrs?: Attrs): SVGElement
export function Anchor(attrs?: Attrs): SVGElement
export function Stairs(attrs?: Attrs): SVGElement
export function CompassRose(attrs?: Attrs): SVGElement
export function ArrowCircleDown(attrs?: Attrs): SVGElement
export function Panorama(attrs?: Attrs): SVGElement
export function Ticket(attrs?: Attrs): SVGElement
export function FileZip(attrs?: Attrs): SVGElement
export function ArrowUp(attrs?: Attrs): SVGElement
export function ArrowDownLeft(attrs?: Attrs): SVGElement
export function FileRs(attrs?: Attrs): SVGElement
export function Warehouse(attrs?: Attrs): SVGElement
export function UserCircleCheck(attrs?: Attrs): SVGElement
export function Snowflake(attrs?: Attrs): SVGElement
export function MedalMilitary(attrs?: Attrs): SVGElement
export function HandWithdraw(attrs?: Attrs): SVGElement
export function FileCode(attrs?: Attrs): SVGElement
export function HandPeace(attrs?: Attrs): SVGElement
export function Plug(attrs?: Attrs): SVGElement
export function ListHeart(attrs?: Attrs): SVGElement
export function Rss(attrs?: Attrs): SVGElement
export function Handshake(attrs?: Attrs): SVGElement
export function CurrencyInr(attrs?: Attrs): SVGElement
export function TriangleDashed(attrs?: Attrs): SVGElement
export function Package(attrs?: Attrs): SVGElement
export function TextB(attrs?: Attrs): SVGElement
export function NotionLogo(attrs?: Attrs): SVGElement
export function HighlighterCircle(attrs?: Attrs): SVGElement
export function CellSignalLow(attrs?: Attrs): SVGElement
export function GreaterThanOrEqual(attrs?: Attrs): SVGElement
export function CircleHalfTilt(attrs?: Attrs): SVGElement
export function Coin(attrs?: Attrs): SVGElement
export function MusicNote(attrs?: Attrs): SVGElement
export function Wheelchair(attrs?: Attrs): SVGElement
export function SquareHalf(attrs?: Attrs): SVGElement
export function PushPinSimple(attrs?: Attrs): SVGElement
export function Vault(attrs?: Attrs): SVGElement
export function Compass(attrs?: Attrs): SVGElement
export function Spade(attrs?: Attrs): SVGElement
export function ListMagnifyingGlass(attrs?: Attrs): SVGElement
export function CodaLogo(attrs?: Attrs): SVGElement
export function TrendUp(attrs?: Attrs): SVGElement
export function CalendarHeart(attrs?: Attrs): SVGElement
export function PersonSimpleThrow(attrs?: Attrs): SVGElement
export function Cylinder(attrs?: Attrs): SVGElement
export function ArrowLineUp(attrs?: Attrs): SVGElement
export function HandArrowUp(attrs?: Attrs): SVGElement
export function Suitcase(attrs?: Attrs): SVGElement
export function SquaresFour(attrs?: Attrs): SVGElement
export function CameraPlus(attrs?: Attrs): SVGElement
export function MapPinSimple(attrs?: Attrs): SVGElement
export function Hospital(attrs?: Attrs): SVGElement
export function ToteSimple(attrs?: Attrs): SVGElement
export function TextAlignRight(attrs?: Attrs): SVGElement
export function Note(attrs?: Attrs): SVGElement
export function Unite(attrs?: Attrs): SVGElement
export function FileCsv(attrs?: Attrs): SVGElement
export function Guitar(attrs?: Attrs): SVGElement
export function Sailboat(attrs?: Attrs): SVGElement
export function Park(attrs?: Attrs): SVGElement
export function Bomb(attrs?: Attrs): SVGElement
export function Sock(attrs?: Attrs): SVGElement
export function Radioactive(attrs?: Attrs): SVGElement
export function Asterisk(attrs?: Attrs): SVGElement
export function Memory(attrs?: Attrs): SVGElement
export function FlowerTulip(attrs?: Attrs): SVGElement
export function FileJsx(attrs?: Attrs): SVGElement
export function Fan(attrs?: Attrs): SVGElement
export function Eject(attrs?: Attrs): SVGElement
export function ChatTeardropDots(attrs?: Attrs): SVGElement
export function SuitcaseRolling(attrs?: Attrs): SVGElement
export function SubtractSquare(attrs?: Attrs): SVGElement
export function StackMinus(attrs?: Attrs): SVGElement
export function ArticleMedium(attrs?: Attrs): SVGElement
export function Bank(attrs?: Attrs): SVGElement
export function Invoice(attrs?: Attrs): SVGElement
export function MaskSad(attrs?: Attrs): SVGElement
export function ChartPolar(attrs?: Attrs): SVGElement
export function Rewind(attrs?: Attrs): SVGElement
export function MediumLogo(attrs?: Attrs): SVGElement
export function ArrowSquareUpLeft(attrs?: Attrs): SVGElement
export function CaretUpDown(attrs?: Attrs): SVGElement
export function Elevator(attrs?: Attrs): SVGElement
export function Campfire(attrs?: Attrs): SVGElement
export function Minus(attrs?: Attrs): SVGElement
export function DropboxLogo(attrs?: Attrs): SVGElement
export function FolderSimpleLock(attrs?: Attrs): SVGElement
export function WaveSawtooth(attrs?: Attrs): SVGElement
export function CookingPot(attrs?: Attrs): SVGElement
export function ArrowUDownRight(attrs?: Attrs): SVGElement
export function Trash(attrs?: Attrs): SVGElement
export function Lighthouse(attrs?: Attrs): SVGElement
export function EscalatorUp(attrs?: Attrs): SVGElement
export function CallBell(attrs?: Attrs): SVGElement
export function FlipHorizontal(attrs?: Attrs): SVGElement
export function Ear(attrs?: Attrs): SVGElement
export function BeerBottle(attrs?: Attrs): SVGElement
export function ArrowsHorizontal(attrs?: Attrs): SVGElement
export function Mailbox(attrs?: Attrs): SVGElement
export function Vignette(attrs?: Attrs): SVGElement
export function Command(attrs?: Attrs): SVGElement
export function YinYang(attrs?: Attrs): SVGElement
export function NumberSquareNine(attrs?: Attrs): SVGElement
export function Needle(attrs?: Attrs): SVGElement
export function ChatCenteredText(attrs?: Attrs): SVGElement
export function PhoneOutgoing(attrs?: Attrs): SVGElement
export function TelegramLogo(attrs?: Attrs): SVGElement
export function DropSlash(attrs?: Attrs): SVGElement
export function TrayArrowUp(attrs?: Attrs): SVGElement
export function AlignCenterHorizontal(attrs?: Attrs): SVGElement
export function Barricade(attrs?: Attrs): SVGElement
export function DropHalfBottom(attrs?: Attrs): SVGElement
export function ArrowUpLeft(attrs?: Attrs): SVGElement
export function Subway(attrs?: Attrs): SVGElement
export function BatteryVerticalMedium(attrs?: Attrs): SVGElement
export function ArrowFatLeft(attrs?: Attrs): SVGElement
export function MouseScroll(attrs?: Attrs): SVGElement
export function GithubLogo(attrs?: Attrs): SVGElement
export function ArrowElbowUpRight(attrs?: Attrs): SVGElement
export function Barn(attrs?: Attrs): SVGElement
export function SignIn(attrs?: Attrs): SVGElement
export function PictureInPicture(attrs?: Attrs): SVGElement
export function Receipt(attrs?: Attrs): SVGElement
export function FolderSimple(attrs?: Attrs): SVGElement
export function AlignTop(attrs?: Attrs): SVGElement
export function Translate(attrs?: Attrs): SVGElement
export function TrolleySuitcase(attrs?: Attrs): SVGElement
export function SquareSplitVertical(attrs?: Attrs): SVGElement
export function Hurricane(attrs?: Attrs): SVGElement
export function PoliceCar(attrs?: Attrs): SVGElement
export function FirstAidKit(attrs?: Attrs): SVGElement
export function CalendarSlash(attrs?: Attrs): SVGElement
export function Cherries(attrs?: Attrs): SVGElement
export function BracketsCurly(attrs?: Attrs): SVGElement
export function DribbbleLogo(attrs?: Attrs): SVGElement
export function HandsClapping(attrs?: Attrs): SVGElement
export function Pizza(attrs?: Attrs): SVGElement
export function GitPullRequest(attrs?: Attrs): SVGElement
export function StandardDefinition(attrs?: Attrs): SVGElement
export function BookBookmark(attrs?: Attrs): SVGElement
export function CloudArrowDown(attrs?: Attrs): SVGElement
export function HighDefinition(attrs?: Attrs): SVGElement
export function WaveformSlash(attrs?: Attrs): SVGElement
export function Pill(attrs?: Attrs): SVGElement
export function Avocado(attrs?: Attrs): SVGElement
export function HandFist(attrs?: Attrs): SVGElement
export function UserSound(attrs?: Attrs): SVGElement
export function SlackLogo(attrs?: Attrs): SVGElement
export function BookOpenText(attrs?: Attrs): SVGElement
export function Signpost(attrs?: Attrs): SVGElement
export function CaretLineLeft(attrs?: Attrs): SVGElement
export function Barcode(attrs?: Attrs): SVGElement
export function MatrixLogo(attrs?: Attrs): SVGElement
export function FileText(attrs?: Attrs): SVGElement
export function FolderSimpleUser(attrs?: Attrs): SVGElement
export function Brandy(attrs?: Attrs): SVGElement
export function SpeakerSlash(attrs?: Attrs): SVGElement
export function SpeakerSimpleSlash(attrs?: Attrs): SVGElement
export function LastfmLogo(attrs?: Attrs): SVGElement
export function HourglassSimpleMedium(attrs?: Attrs): SVGElement
export function ShieldPlus(attrs?: Attrs): SVGElement
export function Hexagon(attrs?: Attrs): SVGElement
export function Peace(attrs?: Attrs): SVGElement
export function ArrowSquareLeft(attrs?: Attrs): SVGElement
export function Plugs(attrs?: Attrs): SVGElement
export function Camera(attrs?: Attrs): SVGElement
export function FaceMask(attrs?: Attrs): SVGElement
export function CaretDoubleUp(attrs?: Attrs): SVGElement
export function Factory(attrs?: Attrs): SVGElement
export function ArrowBendLeftUp(attrs?: Attrs): SVGElement
export function BatteryFull(attrs?: Attrs): SVGElement
export function PencilSlash(attrs?: Attrs): SVGElement
export function PhoneCall(attrs?: Attrs): SVGElement
export function Meteor(attrs?: Attrs): SVGElement
export function HourglassSimple(attrs?: Attrs): SVGElement
export function CaretCircleDoubleRight(attrs?: Attrs): SVGElement
export function TrafficCone(attrs?: Attrs): SVGElement
export function Barbell(attrs?: Attrs): SVGElement
export function SquareHalfBottom(attrs?: Attrs): SVGElement
export function Racquet(attrs?: Attrs): SVGElement
export function GraphicsCard(attrs?: Attrs): SVGElement
export function Certificate(attrs?: Attrs): SVGElement
export function CaretLineDown(attrs?: Attrs): SVGElement
export function MouseMiddleClick(attrs?: Attrs): SVGElement
export function PersonSimpleWalk(attrs?: Attrs): SVGElement
export function Scissors(attrs?: Attrs): SVGElement
export function HandSwipeLeft(attrs?: Attrs): SVGElement
export function Cookie(attrs?: Attrs): SVGElement
export function GooglePodcastsLogo(attrs?: Attrs): SVGElement
export function Newspaper(attrs?: Attrs): SVGElement
export function Money(attrs?: Attrs): SVGElement
export function Kanban(attrs?: Attrs): SVGElement
export function FloppyDiskBack(attrs?: Attrs): SVGElement
export function CellSignalNone(attrs?: Attrs): SVGElement
export function ArrowsDownUp(attrs?: Attrs): SVGElement
export function Bookmark(attrs?: Attrs): SVGElement
export function EggCrack(attrs?: Attrs): SVGElement
export function ListChecks(attrs?: Attrs): SVGElement
export function ChatTeardropText(attrs?: Attrs): SVGElement
export function Umbrella(attrs?: Attrs): SVGElement
export function Download(attrs?: Attrs): SVGElement
export function Option(attrs?: Attrs): SVGElement
export function ClockAfternoon(attrs?: Attrs): SVGElement
export function PawPrint(attrs?: Attrs): SVGElement
export function CaretLineUp(attrs?: Attrs): SVGElement
export function LegoSmiley(attrs?: Attrs): SVGElement
export function Copyright(attrs?: Attrs): SVGElement
export function TextOutdent(attrs?: Attrs): SVGElement
export function Book(attrs?: Attrs): SVGElement
export function SealPercent(attrs?: Attrs): SVGElement
export function CircleHalf(attrs?: Attrs): SVGElement
export function SolarPanel(attrs?: Attrs): SVGElement
export function ArrowSquareDown(attrs?: Attrs): SVGElement
export function LinuxLogo(attrs?: Attrs): SVGElement
export function TrainRegional(attrs?: Attrs): SVGElement
export function Cactus(attrs?: Attrs): SVGElement
export function ArrowURightUp(attrs?: Attrs): SVGElement
export function OrangeSlice(attrs?: Attrs): SVGElement
export function Virus(attrs?: Attrs): SVGElement
export function AlignBottomSimple(attrs?: Attrs): SVGElement
export function NumberCircleFive(attrs?: Attrs): SVGElement
export function LetterCircleH(attrs?: Attrs): SVGElement
export function HourglassMedium(attrs?: Attrs): SVGElement
export function FireExtinguisher(attrs?: Attrs): SVGElement
export function CurrencyRub(attrs?: Attrs): SVGElement
export function TextUnderline(attrs?: Attrs): SVGElement
export function TextHFour(attrs?: Attrs): SVGElement
export function ImageBroken(attrs?: Attrs): SVGElement
export function Video(attrs?: Attrs): SVGElement
export function Plant(attrs?: Attrs): SVGElement
export function GameController(attrs?: Attrs): SVGElement
export function PencilRuler(attrs?: Attrs): SVGElement
export function TextAUnderline(attrs?: Attrs): SVGElement
export function Wall(attrs?: Attrs): SVGElement
export function Person(attrs?: Attrs): SVGElement
export function LetterCircleV(attrs?: Attrs): SVGElement
export function Mosque(attrs?: Attrs): SVGElement
export function CalendarPlus(attrs?: Attrs): SVGElement
export function WheelchairMotion(attrs?: Attrs): SVGElement
export function PatreonLogo(attrs?: Attrs): SVGElement
export function PersonSimpleHike(attrs?: Attrs): SVGElement
export function CloudArrowUp(attrs?: Attrs): SVGElement
export function MusicNotesMinus(attrs?: Attrs): SVGElement
export function Funnel(attrs?: Attrs): SVGElement
export function CraneTower(attrs?: Attrs): SVGElement
export function Bandaids(attrs?: Attrs): SVGElement
export function Voicemail(attrs?: Attrs): SVGElement
export function BatteryMedium(attrs?: Attrs): SVGElement
export function TrendDown(attrs?: Attrs): SVGElement
export function Link(attrs?: Attrs): SVGElement
export function ArrowCircleDownLeft(attrs?: Attrs): SVGElement
export function ProhibitInset(attrs?: Attrs): SVGElement
export function LampPendant(attrs?: Attrs): SVGElement
export function Equalizer(attrs?: Attrs): SVGElement
export function Trophy(attrs?: Attrs): SVGElement
export function Cpu(attrs?: Attrs): SVGElement
export function ArrowFatDown(attrs?: Attrs): SVGElement
export function Volleyball(attrs?: Attrs): SVGElement
export function FileCpp(attrs?: Attrs): SVGElement
export function PaperclipHorizontal(attrs?: Attrs): SVGElement
export function LockLaminated(attrs?: Attrs): SVGElement
export function Tray(attrs?: Attrs): SVGElement
export function ChartDonut(attrs?: Attrs): SVGElement
export function SteeringWheel(attrs?: Attrs): SVGElement
export function ChatCentered(attrs?: Attrs): SVGElement
export function NetworkX(attrs?: Attrs): SVGElement
export function SteamLogo(attrs?: Attrs): SVGElement
export function Cheese(attrs?: Attrs): SVGElement
export function MastodonLogo(attrs?: Attrs): SVGElement
export function Balloon(attrs?: Attrs): SVGElement
export function IdentificationBadge(attrs?: Attrs): SVGElement
export function FileLock(attrs?: Attrs): SVGElement
export function Alarm(attrs?: Attrs): SVGElement
export function Parachute(attrs?: Attrs): SVGElement
export function ListBullets(attrs?: Attrs): SVGElement
export function PhoneTransfer(attrs?: Attrs): SVGElement
export function GasCan(attrs?: Attrs): SVGElement
export function Tent(attrs?: Attrs): SVGElement
export function CircleNotch(attrs?: Attrs): SVGElement
export function AppWindow(attrs?: Attrs): SVGElement
export function Microscope(attrs?: Attrs): SVGElement
export function PencilSimpleSlash(attrs?: Attrs): SVGElement
export function BuildingOffice(attrs?: Attrs): SVGElement
export function CloudMoon(attrs?: Attrs): SVGElement
export function TagChevron(attrs?: Attrs): SVGElement
export function PipeWrench(attrs?: Attrs): SVGElement
export function Angle(attrs?: Attrs): SVGElement
export function Columns(attrs?: Attrs): SVGElement
export function Keyboard(attrs?: Attrs): SVGElement
export function RssSimple(attrs?: Attrs): SVGElement
export function FileIni(attrs?: Attrs): SVGElement
export function Phone(attrs?: Attrs): SVGElement
export function Golf(attrs?: Attrs): SVGElement
export function TagSimple(attrs?: Attrs): SVGElement
export function GlobeStand(attrs?: Attrs): SVGElement
export function GoogleLogo(attrs?: Attrs): SVGElement
export function ChatCircleSlash(attrs?: Attrs): SVGElement
export function PushPinSlash(attrs?: Attrs): SVGElement
export function FileAudio(attrs?: Attrs): SVGElement
export function FolderSimplePlus(attrs?: Attrs): SVGElement
export function UserCircleMinus(attrs?: Attrs): SVGElement
export function NumberTwo(attrs?: Attrs): SVGElement
export function NumberCircleSeven(attrs?: Attrs): SVGElement
export function DesktopTower(attrs?: Attrs): SVGElement
export function TextAa(attrs?: Attrs): SVGElement
export function Tipi(attrs?: Attrs): SVGElement
export function MetaLogo(attrs?: Attrs): SVGElement
export function NumberEight(attrs?: Attrs): SVGElement
export function PhoneList(attrs?: Attrs): SVGElement
export function Carrot(attrs?: Attrs): SVGElement
export function ArrowArcRight(attrs?: Attrs): SVGElement
export function Steps(attrs?: Attrs): SVGElement
export function AirTrafficControl(attrs?: Attrs): SVGElement
export function CalendarMinus(attrs?: Attrs): SVGElement
export function DropHalf(attrs?: Attrs): SVGElement
export function Ghost(attrs?: Attrs): SVGElement
export function Checkerboard(attrs?: Attrs): SVGElement
export function ReplitLogo(attrs?: Attrs): SVGElement
export function HandGrabbing(attrs?: Attrs): SVGElement
export function Cloud(attrs?: Attrs): SVGElement
export function SpeakerLow(attrs?: Attrs): SVGElement
export function BehanceLogo(attrs?: Attrs): SVGElement
export function SolarRoof(attrs?: Attrs): SVGElement
export function ArrowSquareRight(attrs?: Attrs): SVGElement
export function Recycle(attrs?: Attrs): SVGElement
export function ArrowBendDownLeft(attrs?: Attrs): SVGElement
export function Check(attrs?: Attrs): SVGElement
export function Tote(attrs?: Attrs): SVGElement
export function ArrowsClockwise(attrs?: Attrs): SVGElement
export function Magnet(attrs?: Attrs): SVGElement
export function MicrosoftPowerpointLogo(attrs?: Attrs): SVGElement
export function ArrowULeftDown(attrs?: Attrs): SVGElement
export function CoatHanger(attrs?: Attrs): SVGElement
export function AlignRight(attrs?: Attrs): SVGElement
export function TestTube(attrs?: Attrs): SVGElement
export function Sunglasses(attrs?: Attrs): SVGElement
export function Ranking(attrs?: Attrs): SVGElement
export function EyedropperSample(attrs?: Attrs): SVGElement
export function TiktokLogo(attrs?: Attrs): SVGElement
export function GitlabLogoSimple(attrs?: Attrs): SVGElement
export function Radical(attrs?: Attrs): SVGElement
export function ArrowsCounterClockwise(attrs?: Attrs): SVGElement
export function FolderSimpleMinus(attrs?: Attrs): SVGElement
export function PersonSimpleSwim(attrs?: Attrs): SVGElement
export function GitBranch(attrs?: Attrs): SVGElement
export function City(attrs?: Attrs): SVGElement
export function Subtitles(attrs?: Attrs): SVGElement
export function RadioButton(attrs?: Attrs): SVGElement
export function ChartLine(attrs?: Attrs): SVGElement
export function ArrowLineDownLeft(attrs?: Attrs): SVGElement
export function BatteryChargingVertical(attrs?: Attrs): SVGElement
export function SkipForwardCircle(attrs?: Attrs): SVGElement
export function DotsThreeOutlineVertical(attrs?: Attrs): SVGElement
export function LinkSimple(attrs?: Attrs): SVGElement
export function Headphones(attrs?: Attrs): SVGElement
export function ListStar(attrs?: Attrs): SVGElement
export function Sticker(attrs?: Attrs): SVGElement
export function MusicNotesPlus(attrs?: Attrs): SVGElement
export function FrameCorners(attrs?: Attrs): SVGElement
export function Folders(attrs?: Attrs): SVGElement
export function DeviceTabletSpeaker(attrs?: Attrs): SVGElement
export function NuclearPlant(attrs?: Attrs): SVGElement
export function TShirt(attrs?: Attrs): SVGElement
export function Bug(attrs?: Attrs): SVGElement
export function IntersectSquare(attrs?: Attrs): SVGElement
export function Church(attrs?: Attrs): SVGElement
export function EarSlash(attrs?: Attrs): SVGElement
export function FolderMinus(attrs?: Attrs): SVGElement
export function ProjectorScreen(attrs?: Attrs): SVGElement
export function NumberFive(attrs?: Attrs): SVGElement
export function Heart(attrs?: Attrs): SVGElement
export function TumblrLogo(attrs?: Attrs): SVGElement
export function CowboyHat(attrs?: Attrs): SVGElement
export function ChalkboardTeacher(attrs?: Attrs): SVGElement
export function MouseLeftClick(attrs?: Attrs): SVGElement
export function SneakerMove(attrs?: Attrs): SVGElement
export function Lightning(attrs?: Attrs): SVGElement
export function PiggyBank(attrs?: Attrs): SVGElement
export function DeviceTabletCamera(attrs?: Attrs): SVGElement
export function NotePencil(attrs?: Attrs): SVGElement
export function Bathtub(attrs?: Attrs): SVGElement
export function Beanie(attrs?: Attrs): SVGElement
export function Brain(attrs?: Attrs): SVGElement
export function ArrowCircleDownRight(attrs?: Attrs): SVGElement
export function Laptop(attrs?: Attrs): SVGElement
export function WashingMachine(attrs?: Attrs): SVGElement
export function Image(attrs?: Attrs): SVGElement
export function HeartBreak(attrs?: Attrs): SVGElement
export function ArrowCircleUpRight(attrs?: Attrs): SVGElement
export function HeartStraight(attrs?: Attrs): SVGElement
export function Target(attrs?: Attrs): SVGElement
export function NumberSquareOne(attrs?: Attrs): SVGElement
export function GlobeHemisphereWest(attrs?: Attrs): SVGElement
export function SplitHorizontal(attrs?: Attrs): SVGElement
export function Tilde(attrs?: Attrs): SVGElement
export function ThreeD(attrs?: Attrs): SVGElement
export function Percent(attrs?: Attrs): SVGElement
export function CheckFat(attrs?: Attrs): SVGElement
export function UniteSquare(attrs?: Attrs): SVGElement
export function TextHTwo(attrs?: Attrs): SVGElement
export function TwitchLogo(attrs?: Attrs): SVGElement
export function FastForward(attrs?: Attrs): SVGElement
export function FunnelX(attrs?: Attrs): SVGElement
export function Info(attrs?: Attrs): SVGElement
export function SmileyXEyes(attrs?: Attrs): SVGElement
export function PhoneIncoming(attrs?: Attrs): SVGElement
export function GitlabLogo(attrs?: Attrs): SVGElement
export function CalendarDots(attrs?: Attrs): SVGElement
export function Bird(attrs?: Attrs): SVGElement
export function GasPump(attrs?: Attrs): SVGElement
export function PersonSimpleTaiChi(attrs?: Attrs): SVGElement
export function Fire(attrs?: Attrs): SVGElement
export function ArrowSquareUp(attrs?: Attrs): SVGElement
export function HandArrowDown(attrs?: Attrs): SVGElement
export function ChartPie(attrs?: Attrs): SVGElement
export function Dog(attrs?: Attrs): SVGElement
export function TipJar(attrs?: Attrs): SVGElement
export function StarHalf(attrs?: Attrs): SVGElement
export function Pinwheel(attrs?: Attrs): SVGElement
export function BagSimple(attrs?: Attrs): SVGElement
export function LockSimpleOpen(attrs?: Attrs): SVGElement
export function Circuitry(attrs?: Attrs): SVGElement
export function PingPong(attrs?: Attrs): SVGElement
export function CodepenLogo(attrs?: Attrs): SVGElement
export function Clover(attrs?: Attrs): SVGElement
export function HouseLine(attrs?: Attrs): SVGElement
export function NumberSquareSix(attrs?: Attrs): SVGElement
export function FileJpg(attrs?: Attrs): SVGElement
export function CodeSimple(attrs?: Attrs): SVGElement
export function SubtitlesSlash(attrs?: Attrs): SVGElement
export function Lamp(attrs?: Attrs): SVGElement
export function PencilSimpleLine(attrs?: Attrs): SVGElement
export function Confetti(attrs?: Attrs): SVGElement
export function FileArrowUp(attrs?: Attrs): SVGElement
export function PhoneDisconnect(attrs?: Attrs): SVGElement
export function NumberCircleTwo(attrs?: Attrs): SVGElement
export function TreeView(attrs?: Attrs): SVGElement
export function BeerStein(attrs?: Attrs): SVGElement
export function MonitorPlay(attrs?: Attrs): SVGElement
export function EnvelopeOpen(attrs?: Attrs): SVGElement
export function Smiley(attrs?: Attrs): SVGElement
export function SnapchatLogo(attrs?: Attrs): SVGElement
export function FileDashed(attrs?: Attrs): SVGElement
export function Prescription(attrs?: Attrs): SVGElement
export function Boat(attrs?: Attrs): SVGElement
export function PintGlass(attrs?: Attrs): SVGElement
export function MagnifyingGlass(attrs?: Attrs): SVGElement
export function Subtract(attrs?: Attrs): SVGElement
export function BatteryVerticalFull(attrs?: Attrs): SVGElement
export function Sphere(attrs?: Attrs): SVGElement
export function MapPinLine(attrs?: Attrs): SVGElement
export function UserSwitch(attrs?: Attrs): SVGElement
export function PenNib(attrs?: Attrs): SVGElement
export function FileC(attrs?: Attrs): SVGElement
export function UsersThree(attrs?: Attrs): SVGElement
export function BatteryWarningVertical(attrs?: Attrs): SVGElement
export function ArrowFatLinesUp(attrs?: Attrs): SVGElement
export function Numpad(attrs?: Attrs): SVGElement
export function SpinnerBall(attrs?: Attrs): SVGElement
export function Gear(attrs?: Attrs): SVGElement
export function Clipboard(attrs?: Attrs): SVGElement
export function Gavel(attrs?: Attrs): SVGElement
export function PaperPlaneRight(attrs?: Attrs): SVGElement
export function ArrowFatLineRight(attrs?: Attrs): SVGElement
export function ArrowLineUpRight(attrs?: Attrs): SVGElement
export function QuestionMark(attrs?: Attrs): SVGElement
export function Butterfly(attrs?: Attrs): SVGElement
export function FastForwardCircle(attrs?: Attrs): SVGElement
export function ChatCircleDots(attrs?: Attrs): SVGElement
export function PhoneSlash(attrs?: Attrs): SVGElement
export function MapPinSimpleArea(attrs?: Attrs): SVGElement
export function TeaBag(attrs?: Attrs): SVGElement
export function CircleDashed(attrs?: Attrs): SVGElement
export function MicrophoneStage(attrs?: Attrs): SVGElement
export function UserRectangle(attrs?: Attrs): SVGElement
export function CaretUp(attrs?: Attrs): SVGElement
export function ArrowElbowRightDown(attrs?: Attrs): SVGElement
export function Checks(attrs?: Attrs): SVGElement
export function Footprints(attrs?: Attrs): SVGElement
export function BowlSteam(attrs?: Attrs): SVGElement
export function Cheers(attrs?: Attrs): SVGElement
export function NoteBlank(attrs?: Attrs): SVGElement
export function RoadHorizon(attrs?: Attrs): SVGElement
export function GenderNeuter(attrs?: Attrs): SVGElement
export function ArrowSquareOut(attrs?: Attrs): SVGElement
export function WaveSquare(attrs?: Attrs): SVGElement